#! /bin/bash
#
# Clears out Guides Template files and repo for a new Guide.
#
# Author: Mike Bland <michael.bland@gsa.gov>

# Hack per:
# http://stackoverflow.com/questions/4774054/reliable-way-for-a-bash-script-to-get-the-full-path-to-itself
pushd $(dirname $(dirname $0)) >/dev/null
PROJECT_ROOT=$(pwd -P)
popd >/dev/null

TEMPLATE_FILES="\
  pages/child-page.md \
  pages/config.md \
  pages/github.md \
  pages/images.md \
  pages/new-page.md \
  pages/posting.md \
  images/18f-pages.png \
  images/description.png \
  images/gh-add-guide.png \
  images/gh-branches-link.png \
  images/gh-default-branch.png \
  images/gh-settings-button.png \
  images/gh-webhook.png \
  images/images.png"

set -e
pushd $PROJECT_ROOT >/dev/null
echo "Clearing Guides Template files"
rm $TEMPLATE_FILES
echo "Removing old git repository"
rm -rf .git
echo "Creating a new git repository"
git init
echo "Adding files for initial commit"
git add .
popd >/dev/null
echo "All done! Run 'git commit' to create your first commit."
